# Generated by Django 3.2 on 2021-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RD', 'Готов к выдаче'), ('FM', 'Формируется'), ('STP', 'Отправлен в обработку'), ('PD', 'Оплачен'), ('PRD', 'Обработан'), ('CNC', 'Отменен'), ('DVD', 'Выдан')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
