# Generated by Django 3.2 on 2021-07-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Оплачен'), ('PRD', 'Обработан'), ('STP', 'Отправлен в обработку'), ('RD', 'Готов к выдаче'), ('DVD', 'Выдан'), ('CNC', 'Отменен'), ('FM', 'Формируется')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
